version: '3.8'

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MONGO_AUTH: true
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - mongo_volume:/data/db

volumes:
  mongo_volume: