version: '3.8'


services:
  auth-api:
    build:
      context: .
      target: final
      
    ports:
      - 8080:8080
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_DATABASE=postgres
      - PORT=8080
      - APP_ENV=local
      - OTLP_ENDPOINT=jaeger:4318
  
  ## How to use otel-collector?
  otel-collector:
    image: otel/opentelemetry-collector-dev:latest
    ports:
      - 4318:4318
      - 4317:4317
      - 55680:55680
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: :9411
    ports:
      - 16686:16686 
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  #mongo_volume:
  postgres_volume: