receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp/jaeger: 
    endpoint: "jaeger:4317" 
    tls:
      insecure: true
  otlp/jaeger2: 
    endpoint: "jaeger:4318" 
    tls:
      insecure: true